name: Deploy

on:
  pull_request:
    branches:
      - [ main, dev ]

jobs:
  deploy:
    name: AWS EC2 Deployment
    runs-on: ubuntu-latest
    # SET UP ENVIRONMENT IN GITHUB WITH PROPER PRODUCTION DEPLOYMENT ENVIRONMENT VARIABLES
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy to AWS EC2
