name: Pull Request

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Install eslint
        run: npm install eslint

      - name: Run ESLint
        run: eslint . --ext .js,.jsx,.ts,.tsx

  scan:
    name: CodeQL Security Scan
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ javascript ]
        # CodeQL supports [ 'cpp', 'csharp', 'go', 'java', 'javascript', 'python', 'ruby' ]
        # Learn more about CodeQL language support at https://git.io/codeql-language-support

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}
          # If you wish to specify custom queries, you can do so here or in a config file.
          # By default, queries listed here will override any specified in a config file.
          # Prefix the list here with "+" to use these queries and those in the config file.
          # queries: ./path/to/local/query, your-org/your-repo/queries@main

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1

  test:
    name: Testing Suite
    runs-on: ubuntu-latest
    environment: testing

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install

      - name: Setup environment variable file
        run: |
          printf '%s\n' '${{secrets.DOT_ENV}}' > .env

      - name: Run tests
        run: |
          npm test
